### ISSUE TITLE
How to download bovisa_2008_09_01 dataset?

### ISSUE THREAD

**Issue by fightmoney** [hellovuong/ORB_SLAM3_FAST#3]
Hello bro,
Did you download bovisa_2008_09_01 dataset to train ORBVoc.txt?
I cant download it by the torrent. Is there any other way to download it.

**Comment by hellovuong** [comment]
Hello, if you need the vocabulary trained in bovisa_2008_09_01 that is in dbow3 (bin compression) format then the author of [DBoW3](https://github.com/rmsalinas/DBow3) has already provided it. You can download it [here](https://github.com/rmsalinas/DBow3/blob/master/orbvoc.dbow3), FYI: [check here](https://github.com/rmsalinas/DBow3#loadstore-vocabulary)

**Comment by fightmoney** [comment]
Thanks for your replay!
I want to train other description( just like surf) on the same dataset, so I want to download it!

**Comment by hellovuong** [comment]
Then actually I have not attempted to download and train it by myself before, so I have no answer to your question.
